[web_server]
port = 3000

[tuya_devices]
[tuya_devices.home_alarm]
name = "Home Alarm"
type = "99AST"
host = "https://openapi.tuyaeu.com"
client_id = "id123"
secret = "secret123"
device_id = "device123"

[tuya_devices.office_alarm]
name = "Office Alarm"
type = "99AST"
host = "https://openapi.tuyaeu.com"
client_id = "id123"
secret = "secret123"
device_id = "device1234"
